### ISSUE TITLE
Use a library to process the args rather than manually

### ISSUE THREAD

**Issue by shahar481** [shahar481/Fyssl#7]
Should be super easy to google and do, only edit main.go for this

**Comment by amis-shokoohi** [comment]
I would like to work on this issue.
I think std lib _flag_ package does the job too.

**Comment by shahar481** [comment]
If you mean this- https://golang.org/pkg/flag/
then yeah it looks good. If you have any more questions feel free to ask.

**Comment by amis-shokoohi** [comment]
Alright.

**Comment by shahar481** [comment]
Look great

**Comment by amis-shokoohi** [comment]
I get this in digitalocean dashboard: 
**Your PR was submitted to a repository that is not participating in Hacktoberfest.
Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.**

Would you add hacktoberfest to the repository topics.

**Comment by shahar481** [comment]
Gave you the accepted label and added to the project.

**Comment by amis-shokoohi** [comment]
Thank you.
